[package]
name = "migpad"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
migpad-core.workspace = true
migpad-editor.workspace = true
migpad-ui.workspace = true
sys-locale.workspace = true

[build-dependencies]
toml_edit.workspace = true
